services:
  mysql-migration:
    build:
      context: ../../
      dockerfile: .docker/development/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ../..:/workspaces/app:cached
    networks:
      - network_development
    entrypoint: [ "/bin/sh", "-c", "scripts/entrypoint.sh" ]
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env.${APP_ENV}
    command: "sleep infinity"

  # Databases
  mysql:
    image: mysql:9.0
    env_file:
      - .env.${APP_ENV}
    ports:
      - "3306:3306"
    volumes:
      - /var/run/mysqld:/var/run/mysqld
      - data_mysql:/var/lib/mysql
    networks:
      - network_development
    # performans
    mem_limit: 2g
    cpu_shares: 1024
    # check
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      retries: 5
      timeout: 5s

volumes:
  backup:
  logs:
  data_mysql:


networks:
  network_development:
    driver: bridge
