global:
  scrape_interval: 15s
  # evaluation_interval: 15s
  # scrape_timeout: 10s

scrape_configs:
  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # # Prometheus services
  # - job_name: "kafka"
  #   static_configs:
  #     - targets: ["kafka:9092"]

  # - job_name: "mysql"
  #   static_configs:
  #     - targets: ["mysql:3306"]

  # - job_name: "mongo"
  #   static_configs:
  #     - targets: ["mongo:27017"]

  # - job_name: "postgresql"
  #   static_configs:
  #     - targets: ["postgresql:5432"]

  # - job_name: "redis"
  #   static_configs:
  #     - targets: ["redis:6379"]

  # - job_name: "influxdb"
  #   static_configs:
  #     - targets: ["influxdb:8086"]

  # # Extra Services
  # - job_name: "web"
  #   static_configs:
  #     - targets: ["web:80"]
