-- ====================================================================================================
-- file: seed_countries.sql
-- purpose: Insert initial data ( 231 ) into the countries table according to ISO 3166-1 standards.
-- ====================================================================================================
INSERT INTO countries (country_id, country_code, alpha_3, country_name, native_name, region) VALUES
(4, 'AF', 'AFG', 'Afghanistan', 'افغانستان', 'Asia'),
(8, 'AL', 'ALB', 'Albania', 'Shqipëri', 'Europe'),
(12, 'DZ', 'DZA', 'Algeria', 'الجزائر', 'Africa'),
(16, 'AS', 'ASM', 'American Samoa', 'Sāmoa Amerika', 'Oceania'),
(20, 'AD', 'AND', 'Andorra', 'Andorra', 'Europe'),
(24, 'AO', 'AGO', 'Angola', 'Angola', 'Africa'),
(28, 'AG', 'ATG', 'Antigua and Barbuda', 'Antigua and Barbuda', 'North America'),
(32, 'AR', 'ARG', 'Argentina', 'Argentina', 'South America'),
(51, 'AM', 'ARM', 'Armenia', 'Հայաստան', 'Asia'),
(533, 'AW', 'ABW', 'Aruba', 'Aruba', 'North America'),
(36, 'AU', 'AUS', 'Australia', 'Australia', 'Oceania'),
(40, 'AT', 'AUT', 'Austria', 'Österreich', 'Europe'),
(31, 'AZ', 'AZE', 'Azerbaijan', 'Azərbaycan', 'Asia'),
(44, 'BS', 'BHS', 'Bahamas', 'The Bahamas', 'North America'),
(48, 'BH', 'BHR', 'Bahrain', 'البحرين', 'Asia'),
(50, 'BD', 'BGD', 'Bangladesh', 'বাংলাদেশ', 'Asia'),
(52, 'BB', 'BRB', 'Barbados', 'Barbados', 'North America'),
(112, 'BY', 'BLR', 'Belarus', 'Беларусь', 'Europe'),
(56, 'BE', 'BEL', 'Belgium', 'België', 'Europe'),
(84, 'BZ', 'BLZ', 'Belize', 'Belize', 'North America'),
(204, 'BJ', 'BEN', 'Benin', 'Bénin', 'Africa'),
(64, 'BT', 'BTN', 'Bhutan', 'འབྲུག', 'Asia'),
(68, 'BO', 'BOL', 'Bolivia', 'Bolivia', 'South America'),
(535, 'BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, Sint Eustatius en Saba', 'North America'),
(70, 'BA', 'BIH', 'Bosnia and Herzegovina', 'Bosna i Hercegovina', 'Europe'),
(72, 'BW', 'BWA', 'Botswana', 'Botswana', 'Africa'),
(74, 'BV', 'BVT', 'Bouvet Island', 'Bouvetøya', 'Antarctica'),
(76, 'BR', 'BRA', 'Brazil', 'Brasil', 'South America'),
(96, 'BN', 'BRN', 'Brunei Darussalam', 'Brunei', 'Asia'),
(100, 'BG', 'BGR', 'Bulgaria', 'България', 'Europe'),
(854, 'BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Africa'),
(108, 'BI', 'BDI', 'Burundi', 'Burundi', 'Africa'),
(132, 'CV', 'CPV', 'Cabo Verde', 'Cabo Verde', 'Africa'),
(116, 'KH', 'KHM', 'Cambodia', 'កម្ពុជា', 'Asia'),
(120, 'CM', 'CMR', 'Cameroon', 'Cameroun', 'Africa'),
(124, 'CA', 'CAN', 'Canada', 'Canada', 'North America'),
(136, 'KY', 'CYM', 'Cayman Islands', 'Cayman Islands', 'North America'),
(140, 'CF', 'CAF', 'Central African Republic', 'République centrafricaine', 'Africa'),
(148, 'TD', 'TCD', 'Chad', 'Tchad', 'Africa'),
(152, 'CL', 'CHL', 'Chile', 'Chile', 'South America'),
(156, 'CN', 'CHN', 'China', '中国', 'Asia'),
(162, 'CX', 'CXR', 'Christmas Island', 'Christmas Island', 'Asia'),
(166, 'CC', 'CCK', 'Cocos (Keeling) Islands', 'Cocos (Keeling) Islands', 'Asia'),
(170, 'CO', 'COL', 'Colombia', 'Colombia', 'South America'),
(174, 'KM', 'COM', 'Comoros', 'Komori', 'Africa'),
(180, 'CD', 'COD', 'Congo, Democratic Republic of the', 'République démocratique du Congo', 'Africa'),
(178, 'CG', 'COG', 'Congo, Republic of the', 'Congo', 'Africa'),
(184, 'CK', 'COK', 'Cook Islands', 'Cook Islands', 'Oceania'),
(188, 'CR', 'CRI', 'Costa Rica', 'Costa Rica', 'North America'),
(191, 'HR', 'HRV', 'Croatia', 'Hrvatska', 'Europe'),
(192, 'CU', 'CUB', 'Cuba', 'Cuba', 'North America'),
(531, 'CW', 'CUW', 'Curaçao', 'Curaçao', 'North America'),
(196, 'CY', 'CYP', 'Cyprus', 'Κύπρος', 'Asia'),
(203, 'CZ', 'CZE', 'Czech Republic', 'Česká republika', 'Europe'),
(208, 'DK', 'DNK', 'Denmark', 'Danmark', 'Europe'),
(262, 'DJ', 'DJI', 'Djibouti', 'جيبوتي', 'Africa'),
(212, 'DM', 'DMA', 'Dominica', 'Dominica', 'North America'),
(214, 'DO', 'DOM', 'Dominican Republic', 'República Dominicana', 'North America'),
(218, 'EC', 'ECU', 'Ecuador', 'Ecuador', 'South America'),
(818, 'EG', 'EGY', 'Egypt', 'مصر', 'Africa'),
(222, 'SV', 'SLV', 'El Salvador', 'El Salvador', 'North America'),
(226, 'GQ', 'GNQ', 'Equatorial Guinea', 'Guinea Ecuatorial', 'Africa'),
(232, 'ER', 'ERI', 'Eritrea', 'إريتريا', 'Africa'),
(233, 'EE', 'EST', 'Estonia', 'Eesti', 'Europe'),
(748, 'SZ', 'SWZ', 'Eswatini', 'Eswatini', 'Africa'),
(231, 'ET', 'ETH', 'Ethiopia', 'ኢትዮጵያ', 'Africa'),
(238, 'FK', 'FLK', 'Falkland Islands', 'Falkland Islands', 'South America'),
(234, 'FO', 'FRO', 'Faroe Islands', 'Føroyar', 'Europe'),
(242, 'FJ', 'FJI', 'Fiji', 'Fiji', 'Oceania'),
(246, 'FI', 'FIN', 'Finland', 'Suomi', 'Europe'),
(250, 'FR', 'FRA', 'France', 'France', 'Europe'),
(254, 'GF', 'GUF', 'French Guiana', 'Guyane française', 'South America'),
(258, 'PF', 'PYF', 'French Polynesia', 'Polynésie française', 'Oceania'),
(266, 'GA', 'GAB', 'Gabon', 'Gabon', 'Africa'),
(270, 'GM', 'GMB', 'Gambia', 'Gambia', 'Africa'),
(268, 'GE', 'GEO', 'Georgia', 'საქართველო', 'Asia'),
(276, 'DE', 'DEU', 'Germany', 'Deutschland', 'Europe'),
(288, 'GH', 'GHA', 'Ghana', 'Ghana', 'Africa'),
(292, 'GI', 'GIB', 'Gibraltar', 'Gibraltar', 'Europe'),
(300, 'GR', 'GRC', 'Greece', 'Ελλάδα', 'Europe'),
(304, 'GL', 'GRL', 'Greenland', 'Greenland', 'North America'),
(308, 'GD', 'GRD', 'Grenada', 'Grenada', 'North America'),
(312, 'GP', 'GLP', 'Guadeloupe', 'Guadeloupe', 'North America'),
(316, 'GU', 'GUM', 'Guam', 'Guam', 'Oceania'),
(320, 'GT', 'GTM', 'Guatemala', 'Guatemala', 'North America'),
(831, 'GG', 'GGY', 'Guernsey', 'Guernsey', 'Europe'),
(324, 'GN', 'GIN', 'Guinea', 'Guinée', 'Africa'),
(624, 'GW', 'GNB', 'Guinea-Bissau', 'Guiné-Bissau', 'Africa'),
(328, 'GY', 'GUY', 'Guyana', 'Guyana', 'South America'),
(332, 'HT', 'HTI', 'Haiti', 'Haïti', 'North America'),
(334, 'HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard Island and McDonald Islands', 'Antarctica'),
(336, 'VA', 'VAT', 'Holy See', 'Santa Sede', 'Europe'),
(340, 'HN', 'HND', 'Honduras', 'Honduras', 'North America'),
(344, 'HK', 'HKG', 'Hong Kong', '香港', 'Asia'),
(348, 'HU', 'HUN', 'Hungary', 'Magyarország', 'Europe'),
(352, 'IS', 'ISL', 'Iceland', 'Ísland', 'Europe'),
(356, 'IN', 'IND', 'India', 'भारत', 'Asia'),
(360, 'ID', 'IDN', 'Indonesia', 'Indonesia', 'Asia'),
(364, 'IR', 'IRN', 'Iran', 'ایران', 'Asia'),
(368, 'IQ', 'IRQ', 'Iraq', 'العراق', 'Asia'),
(372, 'IE', 'IRL', 'Ireland', 'Éire', 'Europe'),
(376, 'IL', 'ISR', 'Israel', 'ישראל', 'Asia'),
(380, 'IT', 'ITA', 'Italy', 'Italia', 'Europe'),
(388, 'JM', 'JAM', 'Jamaica', 'Jamaica', 'North America'),
(392, 'JP', 'JPN', 'Japan', '日本', 'Asia'),
(832, 'JE', 'JEY', 'Jersey', 'Jersey', 'Europe'),
(400, 'JO', 'JOR', 'Jordan', 'الأردن', 'Asia'),
(398, 'KZ', 'KAZ', 'Kazakhstan', 'Қазақстан', 'Asia'),
(404, 'KE', 'KEN', 'Kenya', 'Kenya', 'Africa'),
(296, 'KI', 'KIR', 'Kiribati', 'Kiribati', 'Oceania'),
(408, 'KP', 'PRK', 'Korea, Democratic People\'s Republic of', '조선민주주의인민공화국', 'Asia'),
(410, 'KR', 'KOR', 'Korea, Republic of', '대한민국', 'Asia'),
(414, 'KW', 'KWT', 'Kuwait', 'الكويت', 'Asia'),
(417, 'KG', 'KGZ', 'Kyrgyzstan', 'Кыргызстан', 'Asia'),
(418, 'LA', 'LAO', 'Lao People\'s Democratic Republic', 'ສປປ ລາວ', 'Asia'),
(428, 'LV', 'LVA', 'Latvia', 'Latvija', 'Europe'),
(422, 'LB', 'LBN', 'Lebanon', 'لبنان', 'Asia'),
(426, 'LS', 'LSO', 'Lesotho', 'Lesotho', 'Africa'),
(430, 'LR', 'LBR', 'Liberia', 'Liberia', 'Africa'),
(434, 'LY', 'LBY', 'Libya', 'ليبيا', 'Africa'),
(438, 'LI', 'LIE', 'Liechtenstein', 'Liechtenstein', 'Europe'),
(440, 'LT', 'LTU', 'Lithuania', 'Lietuva', 'Europe'),
(442, 'LU', 'LUX', 'Luxembourg', 'Luxembourg', 'Europe'),
(446, 'MO', 'MAC', 'Macao', '澳門', 'Asia'),
(450, 'MG', 'MDG', 'Madagascar', 'Madagasikara', 'Africa'),
(454, 'MW', 'MWI', 'Malawi', 'Malawi', 'Africa'),
(458, 'MY', 'MYS', 'Malaysia', 'Malaysia', 'Asia'),
(462, 'MV', 'MDV', 'Maldives', 'Maldives', 'Asia'),
(466, 'ML', 'MLI', 'Mali', 'Mali', 'Africa'),
(470, 'MT', 'MLT', 'Malta', 'Malta', 'Europe'),
(584, 'MH', 'MHL', 'Marshall Islands', 'M̧ajeļ', 'Oceania'),
(474, 'MQ', 'MTQ', 'Martinique', 'Martinique', 'North America'),
(478, 'MR', 'MRT', 'Mauritania', 'موريطانيا', 'Africa'),
(480, 'MU', 'MUS', 'Mauritius', 'Maurice', 'Africa'),
(175, 'YT', 'MYT', 'Mayotte', 'Mayotte', 'Africa'),
(484, 'MX', 'MEX', 'Mexico', 'México', 'North America'),
(583, 'FM', 'FSM', 'Micronesia', 'Micronesia', 'Oceania'),
(498, 'MD', 'MDA', 'Moldova', 'Republica Moldova', 'Europe'),
(492, 'MC', 'MCO', 'Monaco', 'Monaco', 'Europe'),
(496, 'MN', 'MNG', 'Mongolia', 'Монгол', 'Asia'),
(499, 'ME', 'MNE', 'Montenegro', 'Crna Gora', 'Europe'),
(500, 'MS', 'MSR', 'Montserrat', 'Montserrat', 'North America'),
(504, 'MA', 'MAR', 'Morocco', 'المغرب', 'Africa'),
(508, 'MZ', 'MOZ', 'Mozambique', 'Moçambique', 'Africa'),
(104, 'MM', 'MMR', 'Myanmar', 'မြန်မာ', 'Asia'),
(516, 'NA', 'NAM', 'Namibia', 'Namibia', 'Africa'),
(520, 'NR', 'NRU', 'Nauru', 'Nauru', 'Oceania'),
(524, 'NP', 'NPL', 'Nepal', 'नेपाल', 'Asia'),
(528, 'NL', 'NLD', 'Netherlands', 'Nederland', 'Europe'),
(554, 'NZ', 'NZL', 'New Zealand', 'New Zealand', 'Oceania'),
(558, 'NI', 'NIC', 'Nicaragua', 'Nicaragua', 'North America'),
(562, 'NE', 'NER', 'Niger', 'Niger', 'Africa'),
(566, 'NG', 'NGA', 'Nigeria', 'Nigeria', 'Africa'),
(570, 'NU', 'NIU', 'Niue', 'Niue', 'Oceania'),
(574, 'NF', 'NFK', 'Norfolk Island', 'Norfolk Island', 'Oceania'),
(580, 'MP', 'MNP', 'Northern Mariana Islands', 'Northern Mariana Islands', 'Oceania'),
(578, 'NO', 'NOR', 'Norway', 'Norge', 'Europe'),
(512, 'OM', 'OMN', 'Oman', 'عمان', 'Asia'),
(586, 'PK', 'PAK', 'Pakistan', 'پاکستان', 'Asia'),
(585, 'PW', 'PLW', 'Palau', 'Palau', 'Oceania'),
(275, 'PS', 'PSE', 'Palestine, State of', 'فلسطين', 'Asia'),
(591, 'PA', 'PAN', 'Panama', 'Panamá', 'North America'),
(598, 'PG', 'PNG', 'Papua New Guinea', 'Papua New Guinea', 'Oceania'),
(600, 'PY', 'PRY', 'Paraguay', 'Paraguay', 'South America'),
(604, 'PE', 'PER', 'Peru', 'Perú', 'South America'),
(608, 'PH', 'PHL', 'Philippines', 'Pilipinas', 'Asia'),
(612, 'PN', 'PCN', 'Pitcairn', 'Pitcairn Islands', 'Oceania'),
(616, 'PL', 'POL', 'Poland', 'Polska', 'Europe'),
(620, 'PT', 'PRT', 'Portugal', 'Portugal', 'Europe'),
(630, 'PR', 'PRI', 'Puerto Rico', 'Puerto Rico', 'North America'),
(634, 'QA', 'QAT', 'Qatar', 'قطر', 'Asia'),
(638, 'RE', 'REU', 'Réunion', 'Réunion', 'Africa'),
(642, 'RO', 'ROU', 'Romania', 'România', 'Europe'),
(643, 'RU', 'RUS', 'Russian Federation', 'Российская Федерация', 'Europe'),
(646, 'RW', 'RWA', 'Rwanda', 'Rwanda', 'Africa'),
(652, 'BL', 'BLM', 'Saint Barthélemy', 'Saint-Barthélemy', 'North America'),
(654, 'SH', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helena', 'Africa'),
(659, 'KN', 'KNA', 'Saint Kitts and Nevis', 'Saint Kitts and Nevis', 'North America'),
(662, 'LC', 'LCA', 'Saint Lucia', 'Saint Lucia', 'North America'),
(663, 'MF', 'MAF', 'Saint Martin (French part)', 'Saint-Martin (partie française)', 'North America'),
(534, 'SX', 'SXM', 'Saint Martin (Dutch part)', 'Sint Maarten', 'North America'),
(666, 'PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint-Pierre-et-Miquelon', 'North America'),
(882, 'WS', 'WSM', 'Samoa', 'Samoa', 'Oceania'),
(674, 'SM', 'SMR', 'San Marino', 'San Marino', 'Europe'),
(678, 'ST', 'STP', 'Sao Tome and Principe', 'São Tomé e Príncipe', 'Africa'),
(682, 'SA', 'SAU', 'Saudi Arabia', 'المملكة العربية السعودية', 'Asia'),
(686, 'SN', 'SEN', 'Senegal', 'Sénégal', 'Africa'),
(688, 'RS', 'SRB', 'Serbia', 'Srbija', 'Europe'),
(690, 'SC', 'SYC', 'Seychelles', 'Seychelles', 'Africa'),
(694, 'SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'Africa'),
(702, 'SG', 'SGP', 'Singapore', 'Singapore', 'Asia'),
(703, 'SK', 'SVK', 'Slovakia', 'Slovensko', 'Europe'),
(705, 'SI', 'SVN', 'Slovenia', 'Slovenija', 'Europe'),
(090, 'SB', 'SLB', 'Solomon Islands', 'Solomon Islands', 'Oceania'),
(706, 'SO', 'SOM', 'Somalia', 'Soomaaliya', 'Africa'),
(710, 'ZA', 'ZAF', 'South Africa', 'South Africa', 'Africa'),
(239, 'GS', 'SGS', 'South Georgia and the South Sandwich Islands', 'South Georgia and the South Sandwich Islands', 'Antarctica'),
(728, 'SS', 'SSD', 'South Sudan', 'جنوب السودان', 'Africa'),
(724, 'ES', 'ESP', 'Spain', 'España', 'Europe'),
(144, 'LK', 'LKA', 'Sri Lanka', 'ශ්‍රී ලංකාව', 'Asia'),
(729, 'SD', 'SDN', 'Sudan', 'السودان', 'Africa'),
(752, 'SE', 'SWE', 'Sweden', 'Sverige', 'Europe'),
(756, 'CH', 'CHE', 'Switzerland', 'Schweiz', 'Europe'),
(760, 'SY', 'SYR', 'Syrian Arab Republic', 'الجمهورية العربية السورية', 'Asia'),
(158, 'TW', 'TWN', 'Taiwan, Province of China', '台灣', 'Asia'),
(762, 'TJ', 'TJK', 'Tajikistan', 'Тоҷикистон', 'Asia'),
(834, 'TZ', 'TZA', 'Tanzania', 'Tanzania', 'Africa'),
(764, 'TH', 'THA', 'Thailand', 'ประเทศไทย', 'Asia'),
(626, 'TL', 'TLS', 'Timor-Leste', 'Timor-Leste', 'Asia'),
(768, 'TG', 'TGO', 'Togo', 'Togo', 'Africa'),
(772, 'TK', 'TKL', 'Tokelau', 'Tokelau', 'Oceania'),
(776, 'TO', 'TON', 'Tonga', 'Tonga', 'Oceania'),
(780, 'TT', 'TTO', 'Trinidad and Tobago', 'Trinidad and Tobago', 'North America'),
(788, 'TN', 'TUN', 'Tunisia', 'تونس', 'Africa'),
(792, 'TR', 'TUR', 'Turkey', 'Türkiye', 'Asia'),
(795, 'TM', 'TKM', 'Turkmenistan', 'Türkmenistan', 'Asia'),
(796, 'TC', 'TCA', 'Turks and Caicos Islands', 'Turks and Caicos Islands', 'North America'),
(798, 'TV', 'TUV', 'Tuvalu', 'Tuvalu', 'Oceania'),
(800, 'UG', 'UGA', 'Uganda', 'Uganda', 'Africa'),
(804, 'UA', 'UKR', 'Ukraine', 'Україна', 'Europe'),
(784, 'AE', 'ARE', 'United Arab Emirates', 'دولة الإمارات العربية المتحدة', 'Asia'),
(826, 'GB', 'GBR', 'United Kingdom', 'United Kingdom', 'Europe'),
(840, 'US', 'USA', 'United States', 'United States', 'North America'),
(581, 'UM', 'UMI', 'United States Minor Outlying Islands', 'United States Minor Outlying Islands', 'Oceania'),
(858, 'UY', 'URY', 'Uruguay', 'Uruguay', 'South America'),
(860, 'UZ', 'UZB', 'Uzbekistan', 'Узбекистан', 'Asia'),
(548, 'VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Oceania'),
(862, 'VE', 'VEN', 'Venezuela', 'Venezuela', 'South America'),
(704, 'VN', 'VNM', 'Viet Nam', 'Việt Nam', 'Asia'),
(876, 'WF', 'WLF', 'Wallis and Futuna', 'Wallis et Futuna', 'Oceania'),
(732, 'EH', 'ESH', 'Western Sahara', 'الصحراء الغربية', 'Africa'),
(887, 'YE', 'YEM', 'Yemen', 'اليمن', 'Asia'),
(894, 'ZM', 'ZMB', 'Zambia', 'Zambia', 'Africa'),
(716, 'ZW', 'ZWE', 'Zimbabwe', 'Zimbabwe', 'Africa');
-- ====================================================================================================
-- END OF FILE
-- ====================================================================================================