-- ====================================================================================================
-- file: seed_languages.sql
-- purpose: Insert initial data (185) into the languages table
-- ====================================================================================================
INSERT INTO languages (language_id, language_code, alpha_3_code, language_name, native_name) VALUES
(1, 'AA', 'AFA', 'Afar', 'Afar'),
(2, 'AB', 'ABK', 'Abkhazian', 'Аҧсшәа'),
(3, 'AE', 'AVE', 'Avestan', 'Avesta'),
(4, 'AF', 'AFR', 'Afrikaans', 'Afrikaans'),
(5, 'AK', 'AKA', 'Akan', 'Akan'),
(6, 'AM', 'AMH', 'Amharic', 'አማርኛ'),
(7, 'AN', 'ARG', 'Aragonese', 'Aragonés'),
(8, 'AR', 'ARA', 'Arabic', 'العربية'),
(9, 'AS', 'ASM', 'Assamese', 'অসমীয়া'),
(10, 'AV', 'AVA', 'Avaric', 'Авар'),
(11, 'AY', 'AYM', 'Aymara', 'Aymara'),
(12, 'AZ', 'AZE', 'Azerbaijani', 'Azərbaycan'),
(13, 'BA', 'BAK', 'Bashkir', 'Башҡорт'),
(14, 'BE', 'BEL', 'Belarusian', 'Беларуская'),
(15, 'BG', 'BUL', 'Bulgarian', 'Български'),
(16, 'BH', 'BHO', 'Bhojpuri', 'भोजपुरी'),
(17, 'BI', 'BIS', 'Bislama', 'Bislama'),
(18, 'BM', 'BAM', 'Bambara', 'Bamanankan'),
(19, 'BN', 'BEN', 'Bengali', 'বাংলা'),
(20, 'BO', 'TIB', 'Tibetan', 'བོད་ཡིག'),
(21, 'BR', 'BRN', 'Breton', 'Brezhoneg'),
(22, 'BS', 'BOS', 'Bosnian', 'Bosanski'),
(23, 'CA', 'CAT', 'Catalan', 'Català'),
(24, 'CE', 'CHE', 'Chechen', 'Нохчийн'),
(25, 'CH', 'CHA', 'Chamorro', 'Chamoru'),
(26, 'CO', 'CORS', 'Corsican', 'Corsu'),
(27, 'CR', 'CRE', 'Cree', 'ᓀᐦᐃᔭ'),
(28, 'CS', 'CZE', 'Czech', 'Čeština'),
(29, 'CU', 'CHR', 'Church Slavic', 'Церковнословенский'),
(30, 'CV', 'CHU', 'Chuvash', 'Чӑваш'),
(31, 'CY', 'WEL', 'Welsh', 'Cymraeg'),
(32, 'DA', 'DAN', 'Danish', 'Dansk'),
(33, 'DE', 'DEU', 'German', 'Deutsch'),
(34, 'DV', 'DIV', 'Divehi', 'ދިވެހި'),
(35, 'DZ', 'DZO', 'Dzongkha', 'རྫོང་ཁ'),
(36, 'EE', 'EWE', 'Ewe', 'Eʋe'),
(37, 'EL', 'GRE', 'Greek', 'Ελληνικά'),
(38, 'EN', 'ENG', 'English', 'English'),
(39, 'EO', 'ESP', 'Esperanto', 'Esperanto'),
(40, 'ES', 'SPA', 'Spanish', 'Español'),
(41, 'ET', 'EST', 'Estonian', 'Eesti'),
(42, 'EU', 'BAQ', 'Basque', 'Euskara'),
(43, 'FA', 'PER', 'Persian', 'فارسی'),
(44, 'FF', 'FUL', 'Fulah', 'Fulfulde'),
(45, 'FI', 'FIN', 'Finnish', 'Suomi'),
(46, 'FJ', 'FJI', 'Fijian', 'Na Vosa Vakaviti'),
(47, 'FO', 'FAR', 'Faroese', 'Føroyskt'),
(48, 'FR', 'FRA', 'French', 'Français'),
(49, 'FY', 'FRY', 'Frisian', 'Frysk'),
(50, 'GA', 'GLE', 'Irish', 'Gaeilge'),
(51, 'GD', 'GLG', 'Scottish Gaelic', 'Gàidhlig'),
(52, 'GL', 'GLA', 'Galician', 'Galego'),
(53, 'GN', 'GUA', 'Guarani', 'Aña'),
(54, 'GU', 'GUJ', 'Gujarati', 'ગુજરાતી'),
(55, 'GV', 'GLV', 'Manx', 'Gaelg'),
(56, 'HA', 'HAU', 'Hausa', 'Hausa'),
(57, 'HE', 'HEB', 'Hebrew', 'עברית'),
(58, 'HI', 'HIN', 'Hindi', 'हिन्दी'),
(59, 'HO', 'HOB', 'Hiri Motu', 'Hiri Motu'),
(60, 'HR', 'HRV', 'Croatian', 'Hrvatski'),
(61, 'HT', 'HAT', 'Haitian', 'Kreyòl'),
(62, 'HU', 'HUN', 'Hungarian', 'Magyar'),
(63, 'HY', 'HYE', 'Armenian', 'Հայերեն'),
(64, 'HZ', 'HER', 'Herero', 'Otjiherero'),
(65, 'IA', 'INA', 'Interlingua', 'Interlingua'),
(66, 'ID', 'IND', 'Indonesian', 'Bahasa Indonesia'),
(67, 'IE', 'ILE', 'Interlingue', 'Interlingue'),
(68, 'IG', 'IGE', 'Igbo', 'Igbo'),
(69, 'II', 'III', 'Sichuan Yi', 'ꆈꌠꉙ'),
-- (70, 'IK', 'IKU', 'Inupiat', 'Iñupiatun'),
-- (71, 'IN', 'IND', 'Indonesian', 'Bahasa Indonesia'),
(72, 'IS', 'ICE', 'Icelandic', 'Íslenska'),
(73, 'IT', 'ITA', 'Italian', 'Italiano'),
(74, 'IU', 'IKU', 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ'),
-- (75, 'IW', 'HEB', 'Hebrew', 'עברית'),
(76, 'JA', 'JPN', 'Japanese', '日本語'),
(77, 'JE', 'JEP', 'Jèrriais', 'Jèrriais'),
(78, 'JV', 'JAV', 'Javanese', 'Basa Jawa'),
(79, 'KA', 'KAT', 'Georgian', 'ქართული'),
-- (80, 'KB', 'KUA', 'Kukuya', 'Kukuya'),
(81, 'KE', 'KIK', 'Kikuyu', 'Gĩkuyu'),
(82, 'KG', 'KNG', 'Kongo', 'KiKongo'),
-- (83, 'KI', 'KIR', 'Kirghiz', 'Кыргызча'),
(84, 'KJ', 'KUA', 'Kuanyama', 'Kuanyama'),
(85, 'KL', 'KAL', 'Kalaallisut', 'Kalaallisut'),
(86, 'KM', 'KHM', 'Khmer', 'ខ្មែរ'),
(87, 'KN', 'KAN', 'Kannada', 'ಕನ್ನಡ'),
(88, 'KO', 'KOR', 'Korean', '한국어'),
(89, 'KR', 'KRI', 'Kanuri', 'Kanuri'),
(90, 'KS', 'KAS', 'Kashmiri', 'कश्मीरी'),
(91, 'KT', 'KUT', 'Kutenai', 'Kutenai'),
(92, 'KU', 'KUR', 'Kurdish', 'Kurdî'),
(93, 'KV', 'KOM', 'Komi', 'Коми'),
(94, 'KW', 'CORN', 'Cornish', 'Kernewek'),
(95, 'KY', 'KIR', 'Kirghiz', 'Кыргызча'),
(96, 'LA', 'LAT', 'Latin', 'Latina'),
(97, 'LB', 'LUX', 'Luxembourgish', 'Lëtzebuergesch'),
(98, 'LG', 'LUG', 'Ganda', 'Luganda'),
(99, 'LI', 'LIM', 'Limburgish', 'Limburgs'),
(100, 'LN', 'LIN', 'Lingala', 'Lingála'),
(101, 'LO', 'LAO', 'Lao', 'ລາວ'),
(102, 'LT', 'LIT', 'Lithuanian', 'Lietuvių'),
(103, 'LU', 'LTZ', 'Luxembourgish', 'Lëtzebuergesch'),
(104, 'LV', 'LAV', 'Latvian', 'Latviešu'),
-- (105, 'MG', 'MAL', 'Malagasy', 'Malagasy'),
(106, 'MH', 'MAH', 'Marshallese', 'Kajin M̧ajeļ'),
(107, 'MI', 'MAO', 'Maori', 'Te Reo Māori'),
(108, 'MK', 'MKD', 'Macedonian', 'Македонски'),
(109, 'ML', 'MAL', 'Malayalam', 'മലയാളം'),
(110, 'MN', 'MON', 'Mongolian', 'Монгол'),
(111, 'MO', 'MNI', 'Manipuri', 'মণিপুরী'),
(112, 'MR', 'MAR', 'Marathi', 'मराठी'),
(113, 'MS', 'MSA', 'Malay', 'Bahasa Melayu'),
(114, 'MT', 'MLT', 'Maltese', 'Malti'),
(115, 'MU', 'MUL', 'Multiple languages', 'Múltipla Linguas'),
(116, 'MY', 'BUR', 'Burmese', 'မြန်မာ'),
(117, 'NA', 'NAU', 'Nauru', 'Nauruan'),
(118, 'NB', 'NOB', 'Norwegian Bokmål', 'Norsk bokmål'),
(119, 'ND', 'NDE', 'North Ndebele', 'Sindebele'),
(120, 'NE', 'NEP', 'Nepali', 'नेपाली'),
(121, 'NG', 'NDI', 'Ndonga', 'Oshindonga'),
(122, 'NL', 'NLD', 'Dutch', 'Nederlands'),
(123, 'NN', 'NNO', 'Norwegian Nynorsk', 'Norsk nynorsk'),
(124, 'NO', 'NOR', 'Norwegian', 'Norsk'),
-- (125, 'NR', 'NDE', 'South Ndebele', 'Sindebele'),
(126, 'NV', 'NAV', 'Navajo', 'Diné bizaad'),
(127, 'NY', 'NYA', 'Chichewa', 'Chichewa'),
(128, 'OC', 'OCC', 'Occitan', 'Occitan'),
(129, 'OJ', 'OJI', 'Ojibwa', 'ᐊᓂᔭᐦᑕ'),
(130, 'OM', 'ORM', 'Oromo', 'Afaan Oromoo'),
(131, 'OR', 'ORI', 'Oriya', 'ଓଡ଼ିଆ'),
(132, 'OS', 'OSS', 'Ossetian', 'Ирон'),
(133, 'PA', 'PAN', 'Panjabi', 'ਪੰਜਾਬੀ'),
(134, 'PI', 'PLI', 'Pali', 'पाळि'),
(135, 'PL', 'POL', 'Polish', 'Polski'),
(136, 'PS', 'PAS', 'Pashto', 'پښتو'),
(137, 'PT', 'POR', 'Portuguese', 'Português'),
(138, 'QU', 'QUE', 'Quechua', 'Runa Simi'),
(139, 'RM', 'RHA', 'Romansh', 'Rumantsch'),
(140, 'RN', 'RNT', 'Rundi', 'Ikirundi'),
(141, 'RO', 'RON', 'Romanian', 'Română'),
(142, 'RU', 'RUS', 'Russian', 'Русский'),
-- (143, 'RW', 'KIR', 'Kinyarwanda', 'Ikinyarwanda'),
(144, 'SA', 'SAN', 'Sanskrit', 'संस्कृतम्'),
(145, 'SC', 'SIC', 'Sardinian', 'Sardu'),
(146, 'SD', 'SND', 'Sindhi', 'سنڌي'),
(147, 'SE', 'SME', 'Northern Sami', 'Davvisámegiella'),
(148, 'SG', 'SAG', 'Sango', 'Sango'),
(149, 'SI', 'SIN', 'Sinhala', 'සිංහල'),
(150, 'SK', 'SLK', 'Slovak', 'Slovenčina'),
(151, 'SL', 'SLV', 'Slovenian', 'Slovenščina'),
(152, 'SM', 'SMO', 'Samoan', 'Gagana Samoa'),
(153, 'SN', 'SNA', 'Shona', 'ChiShona'),
(154, 'SO', 'SOM', 'Somali', 'Soomaali'),
(155, 'SQ', 'ALB', 'Albanian', 'Shqip'),
(156, 'SR', 'SRP', 'Serbian', 'Српски'),
(157, 'SS', 'SSW', 'Swati', 'SiSwati'),
(158, 'ST', 'SOT', 'Sotho', 'Sesotho'),
(159, 'SU', 'SUN', 'Sundanese', 'Basa Sunda'),
(160, 'SV', 'SWE', 'Swedish', 'Svenska'),
(161, 'SW', 'SWA', 'Swahili', 'Kiswahili'),
(162, 'SY', 'SYR', 'Syriac', 'ܣܘܪܝܐ'),
(163, 'TA', 'TAM', 'Tamil', 'தமிழ்'),
(164, 'TE', 'TEL', 'Telugu', 'తెలుగు'),
(165, 'TG', 'TJK', 'Tajik', 'Тоҷикӣ'),
(166, 'TH', 'THA', 'Thai', 'ไทย'),
(167, 'TI', 'TIG', 'Tigrinya', 'ትigrinya'),
(168, 'TK', 'TKM', 'Turkmen', 'Türkmen'),
(169, 'TL', 'TLH', 'Klingon', 'tlhIngan'),
(170, 'TN', 'TSN', 'Tswana', 'Setswana'),
(171, 'TO', 'TON', 'Tongan', 'Faka Tonga'),
(172, 'TR', 'TUR', 'Turkish', 'Türkçe'),
(173, 'TS', 'TSON', 'Tsonga', 'Xitsonga'),
(174, 'TT', 'TAT', 'Tatar', 'Татарча'),
(175, 'TU', 'TUM', 'Tumbuka', 'Chitumbuka'),
(176, 'TV', 'TUV', 'Tuvaluan', 'Te taura'),
(177, 'TW', 'TWI', 'Twi', 'Twi'),
(178, 'TY', 'TAH', 'Tahitian', 'Reo Mā’ohi'),
(179, 'UG', 'UIG', 'Uyghur', 'ئۇيغۇرچە'),
(180, 'UK', 'UKR', 'Ukrainian', 'Українська'),
(181, 'UR', 'URD', 'Urdu', 'اردو'),
(182, 'UZ', 'UZB', 'Uzbek', 'Oʻzbek'),
(183, 'VE', 'VEN', 'Venda', 'Tshi'),
(184, 'VI', 'VIE', 'Vietnamese', 'Tiếng Việt'),
(185, 'VO', 'VOL', 'Volapük', 'Volapük'),
(186, 'WA', 'WAL', 'Walloon', 'Walon'),
(187, 'WO', 'WOL', 'Wolof', 'Wollof'),
(188, 'XH', 'XHO', 'Xhosa', 'isiXhosa'),
(189, 'YI', 'YID', 'Yiddish', 'ייִדיש'),
(190, 'YO', 'YOR', 'Yoruba', 'Yorùbá'),
(191, 'ZA', 'ZHA', 'Zhuang', 'Cuengh'),
(192, 'ZH', 'ZHO', 'Chinese', '中文'),
(193, 'ZU', 'ZUL', 'Zulu', 'isiZulu');
-- ====================================================================================================
-- END OF FILE
-- ====================================================================================================